[package]
cairo-version = "2.4.0"
name = "castle_hexapolis"
version = "0.1.0"

[cairo]
sierra-replace-ids = true

[dependencies]
dojo = { git = "https://github.com/dojoengine/dojo", tag = "v0.4.1" }
cubit = { git = "https://github.com/akhercha/cubit", rev = "d3869a3f0c47e5ed229bbbfe2fce3fc0510cbc8a" }

[[target.dojo]]

[tool.dojo]
initializer_class_hash = "0xbeef"

[tool.dojo.env]
# Default account for katana with seed = 0
# rpc_url = "http://localhost:5050/"
# account_address = "0x517ececd29116499f4a1b64b094da79ba08dfd54a3edaa316134c41f8160973"
# private_key = "0x1800000000300000180000000000030000000000003006001800006600"

# slot deploy
rpc_url = "https://api.cartridge.gg/x/castle-hexapolis/katana"
account_address = "0x1872d38801be6a0150c3140a8deab45c14415dedf97446fa3aed2ab9867bb1f"
private_key = "0x5ef37f38f59526582197b050380db86a85f3de7cbd02419b914ea2f90f227f1"
# world = "0xb18e8ef76b6739c501ccb7be5121704babacc68976b4b07789e3a366e68b15"

[tool.dojo.world]
name = "Castle Hexapolis"
description = "An on-chain strategic city development game"
icon_uri = "file://assets/castle_hexapolis_icon.png"
cover_uri = "file://assets/castle_hexapolis_cover.png"
website = "https://castle-hexapolis.vercel.app/"
socials.x = "https://twitter.com/satyambnsal"
socials.github = "https://github.com/satyambnsal/castle-hexapolis"
